language: node_js
node_js:
  - 8
sudo: required
services:
  - docker
before_install:
  - yarn install
  - node scripts/build-docker.js
script:
  - docker run -it --rm -v $PWD:/app cgjs-examples-ubuntu:17.10 /bin/bash -c "gjs --version && yarn install && yarn test"
  - docker run -it --rm -v $PWD:/app cgjs-examples-debian:sid /bin/bash -c "gjs --version && yarn install && yarn test"
