sudo: required
services:
  - docker
matrix:
  include:
    - env: DOCKER_IMAGE=ewnd9/gjs-examples:ubuntu-17.10
    - env: DOCKER_IMAGE=ewnd9/gjs-examples:debian-sid
script:
  - docker run -it --rm -v $PWD:/app $DOCKER_IMAGE /bin/bash -c "gjs --version && yarn install && yarn test"
